name: Generate Snake

on:
  schedule:
    - cron: "59 23 * * *"  # roda todo dia às 23:59
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Generate Snake SVG
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: patix0gui
          outputs: |
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark&color_bg=transparent
            dist/github-contribution-grid-snake-light.svg?palette=github-light&color_bg=transparent

      - name: Commit and push SVGs
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          mkdir -p dist
          git add dist/github-contribution-grid-snake-*.svg
          git diff --cached --quiet || git commit -m "Update GitHub Snake [skip ci]"
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
