name: Generate Snake

on:
  schedule:
    - cron: "59 23 * * *"  # roda todo dia às 23:59
  workflow_dispatch:        # permite rodar manualmente

jobs:
  generate:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      # Faz checkout do repositório
      - name: Checkout repository
        uses: actions/checkout@v3

      # Gera a animação da cobrinha com fundo transparente
      - name: Generate Snake SVG
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: patix0gui
          outputs: dist/github-contribution-grid-snake.svg?palette=github-dark&color_bg=transparent

      # Commit e push para o branch main
      - name: Commit and push SVG
        run: |
          mkdir -p dist
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add dist/github-contribution-grid-snake.svg || true
          git commit -m "Update GitHub Snake [skip ci]" || echo "no changes"
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

